1) Why we need to use sys.exit(1)
2) print ("Unexpected error:", sys.exc_info()[0])
    #What is the last factor we are using [0] in above statement